config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :listings

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'home/index'
  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :listings

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.fetch(:listing, {}).permit(:title, :description, :image)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
  end

  def login
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/about.html.erb
<p>
	Something about us
</p>

app/views/home/index.html.erb
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--5-col mdl-cell--6-col-phone">
        <h3>Find your garden.</h3>
        <form action="#">
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="text" id="sample3">
                <label class="mdl-textfield__label" for="sample3">Where would you like to garden?</label>
            </div>

            <p style="width:300px">
                Size:
                <input class="mdl-slider mdl-js-slider" type="range" id="s1" min="0" max="10" value="4" step="2">
            </p>

            <%= link_to "Search", listings_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent fullwidth"%>

        </form>

    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "beets.jpg", :class => "content-img" %>
    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "Tomatoes.jpg", :class => "content-img" %>
    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "Tomatoes.jpg", :class => "content-img" %>
    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "beets.jpg", :class => "content-img" %>
    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "beets.jpg", :class => "content-img" %>
    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "Tomatoes.jpg", :class => "content-img" %>
    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "Tomatoes.jpg", :class => "content-img" %>
    </div>
    <div class="mdl-cell mdl-cell--2-col-phone">
        <%= image_tag "beets.jpg", :class => "content-img" %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", { :controller => "home", :action => "index" }, :class => "mdl-navigation__link" %>
<%= link_to "About Us", { :controller => "home", :action => "about" }, :class => "mdl-navigation__link" %>
<% if user_signed_in? %>
<%= link_to "Listings", { :controller => "listings" }, :class => "mdl-navigation__link" %>
<% else %>
<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, :class => "mdl-navigation__link" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>UrbShare</title>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
        <link href='http://fonts.which is googleapis.com/css?family=Roboto:400,300,300italic,500,400italic,700,700italic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="//storage.googleapis.com/code.getmdl.io/1.0.1/material.teal-red.min.css"/>
        <script src="//storage.googleapis.com/code.getmdl.io/1.0.1/material.min.js"></script>
    </head>
    <body>
        <!-- Always shows a header, even in smaller screens. -->
        <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
            <header class="mdl-layout__header">
                <div class="mdl-layout__header-row">
                    <!-- Title -->
                    <span class="mdl-layout-title">UrbShare</span>
                    <!-- Add spacer, to align navigation to the right -->
                    <div class="mdl-layout-spacer"></div>
                    <!-- Navigation. We hide it in small screens. -->
                    <nav class="mdl-navigation mdl-layout--large-screen-only">
                        <%= render 'layouts/navigation' %>
                    </nav>
                </div>
            </header>
            <div class="mdl-layout__drawer">
                <span class="mdl-layout-title">UrbShare</span>
                <nav class="mdl-navigation">
                    <%= render 'layouts/navigation' %>
                </nav>
            </div>
            <main class="mdl-layout__content">
                <div class="page-content">
                    <%= yield %>
                </div>
            </main>
        </div>
    </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for @listing, html: { multipart: true } do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title, label: 'Property Name', error: 'Property name is mandatory, please specify one' %>
  <%= f.input :description %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<div class="mdl-grid">
  <% @listings.each do |listing| %>
    <%= link_to listing_path(listing), class: 'mdl-cell mdl-cell--4-col mdl-cell--6-col-tablet mdl-cell--12-col-phone mdl-card mdl-shadow--2dp' do %>
      <div class="mdl-card__media">
        <%= image_tag listing.image.url :thumb %>
      </div>
      <div class="mdl-card__title">
        <h2 class="mdl-card__title-text"><%= listing.title %></h2>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to 'New Listing', new_listing_path %>
<button class="mdl-button mdl-js-button mdl-button--raised">
  
</button>

app/views/listings/new.html.erb
<div class="mdl-card mdl-shadow--6dp">
	<div class="mdl-card__title mdl-color--primary mdl-color-text--white">
		<h2 class="mdl-card__title-text">New Listing</h2>
	</div>
	<div class="mdl-card__supporting-text">
		<%= simple_form_for @listing do |f| %>
			<div class="mdl-textfield mdl-js-textfield">
				<%= f.input :title, label: 'Name', :input_html => { :class => 'mdl-textfield__input' } %>
				<%= f.input :description, label: 'Description', :input_html => { :class => 'mdl-textfield__input' } %>
				<%= f.input :image, :input_html => { :class => 'mdl-textfield__input' } %>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<%= f.button :submit, :input_html => { :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' } %>
			</div>
		<% end %>
	</div>
</div>

<%= link_to "Back", listings_path, :class => "mdl-navigation__link" %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @listing.title %></h1>
<%= simple_format @listing.description %>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="J2KG38PMKU8EE">
<input type="hidden" name="amount" value="30">
<button name="submit" type="submit">Request to Rent</button>
<!--<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">-->
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

<p>Login to your account</p>

app/views/users/signup.html.erb
<h1>Users#signup</h1>
<p>Find me in app/views/users/signup.html.erb</p>

<p>Sign up and you can rent garden space or offer garden space for rent!</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>